parameters:
#    manuel_personas.example.class: Manuel\PersonasBundle\Example

services:
#    manuel_personas.example:
#        class: %manuel_personas.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
