ManuelPersonasBundle:
    resource: "@ManuelPersonasBundle/Resources/config/routing.yml"
    prefix:   /manuel/crud

ManuelInicioBundle:
    resource: "@ManuelInicioBundle/Resources/config/routing.yml"
    prefix:   /manuel

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
